import { connectCloud } from "../config/cloudinary.config.js";
import UploadModel from "../model/upload.model.js";

export const uploadImagde = async (req, res) => {
    try {
        const image = req.file;
        const user = req.user; // Assuming authentication middleware sets req.user
        const { name, description } = req.body;

        if (!image) {
            return res.status(400).json({ message: "File upload failed. No file provided." });
        }
        if(!name ||  !description){
            return res.status(400).json({ message: "Name and Descriptions are also required." });
        }
        // Save the image details to the database
        const result = await connectCloud().uploader.upload(req.file.path, {
            folder:'uploads'
        })
        const newImage = await UploadModel.create({
            image: result.secure_url,//`uploads/${req.file.filename}`, // Save the file name generated by Multer
            name,
            description,
            uploadedBy: user?.id, // Add user ID if authenticated
        });

        return res.status(201).json({ message: "Image uploaded successfully.", data: newImage });
    } catch (error) {
        console.log(error)
        return res.status(500).json({ message: "Server error.", error: error.message });
    }
};


export const getImages = async (req, res)=> {
    try {
        const images = await UploadModel.find()
        if(!images){
            return res.status(404).json({message:"No image found"})
        }
        return res.status(200).json({message:"Images retrieved", images})
    } catch (error) {
        return res.status(500).json({message:error})
    }
}